global_costmap:
  #Set the global and robot frames for the costmap
  global_frame: map
  robot_base_frame: base_footprint

  #Set the update and publish frequency of the costmap
  update_frequency: 1.0 # was 1 
  publish_frequency: 0.5


  #We'll use a map served by the map_server to initialize this costmap
  # static_map: true
  rolling_window: false 
  transform_tolerance: 3.5 
  footprint_padding: 0.02
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"} #static map

     - {name: laser_layer,             type: "costmap_2d::ObstacleLayer"} #laser use on walls and objects

     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"} #inflation layer

    #  - {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}

  